use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
source 'https://code.qburst.com/subinsjose/Specs.git'

target 'SJRefresh_Example' do
  pod 'SJRefresh', :path => '../'
  pod 'Alamofire', '4.0.1'
  pod 'AlamofireImage', '3.1'
end
